services:
  - type: web
    name: leo-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_S3_BUCKET_NAME
        sync: false
      - key: AWS_S3_REGION_NAME
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: FLASK_SECRET_KEY
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: TEMP_PROCESSING_FOLDER
        sync: false

  - type: web
    name: leo-frontend
    env: node
    buildCommand: "npm install && npm run build"
    startCommand: "npm run start"
    envVars:
      - key: NEXT_PUBLIC_FLASK_API_URL
        value: "https://leo-api-ryzd.onrender.com"
